import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderForHome from "@/components/HeaderForHome";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
const clashDisplayBold = localFont({
  src: "./../../public/fonts/ClashDisplay-Bold.eot",
  variable: "--ClashDisplay-Bold",
  style: "normal",
  weight: "100 900",
});

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${clashDisplayBold.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderForHome />
        {children}
      </body>
    </html>
  );
}
